name: Build React App12

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'  # Update this to the latest Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

      - name: Install Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
          unzip dependency-check-10.0.4-release.zip
          sudo mv dependency-check /usr/local/bin/
          chmod +x /usr/local/bin/dependency-check/bin/dependency-check.sh

      - name: Run Dependency-Check
        run: |
          /usr/local/bin/dependency-check/bin/dependency-check.sh \
            --project "FE" \
            --scan . \
            --format HTML \
            --out dependency-check-report.html

      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarQube analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=javascript \
            -Dsonar.projectName='javascript' \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://29ed-59-145-123-10.ngrok-free.app \
            -Dsonar.token=sqp_a986e57c25e5195f761e01f4723e89479f49c49d \
            -Dsonar.javascript.node.maxspace=8192 \
            -Dsonar.dependencyCheck.summarize=true \
            -Dsonar.dependencyCheck.htmlReportPath=dependency-check-report.html 
